# Generated by Django 4.1.1 on 2022-09-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='descriptions',
            new_name='description',
        ),
    ]
